spring:
  kafka:
    consumer:
      group-id: amit-producers
      auto-offset-reset: earliest
    # change this property if you are using your own
    # Kafka cluster or your Docker IP is different
    bootstrap-servers: localhost:9092

amit:
  topic-name: amit-test
  messages-per-request: 10